# Generated by Django 5.0.1 on 2025-01-24 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchitem',
            name='description',
        ),
    ]
